// R257: pulse-cf-worker — adds custom fetch handler so /api/auth/* routes
// go to a TypeScript router (with D1 + Resend bindings), while everything
// else falls through to the static assets directory (../pulse-landing/dist).
//
// Why a custom handler: Workers Static Assets alone cannot host API routes.
// The [[assets]] config serves files from disk; a [[env.production]] route
// can intercept paths and either respond (this file) or call env.ASSETS.fetch(req)
// to forward to the static handler.

import { handleApi } from './api/router';

export interface Env {
	// D1 binding (pulse-db) — see wrangler.toml [[d1_databases]] block.
	DB: D1Database;
	// Secrets — see `wrangler secret put` in deploy checklist.
	RESEND_API_KEY: string;
	FROM_EMAIL: string;
	PUBLIC_APP_URL: string;
	// Optional dev fallback (no key in local): set to "1" to log emails to console.
	DEV_LOG_EMAIL?: string;
	// Static assets binding (auto-generated by Wrangler from [[assets]] block).
	ASSETS: Fetcher;
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);

		// /api/* → custom router (D1 + email + sessions)
		if (url.pathname.startsWith('/api/')) {
			return handleApi(request, env, ctx);
		}

		// Everything else → static assets (Astro build output)
		// env.ASSETS.fetch returns a 404 if file not found; that's the right behavior
		// for SPA-style routing (Astro pre-renders each route to its own /<route>/index.html).
		return env.ASSETS.fetch(request);
	},
} satisfies ExportedHandler<Env>;
